stages:
  get_data:
    cmd: poetry run python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - output/dataset.csv
  preprocess_data:
    cmd: poetry run python src/preprocess_data.py
    deps:
    - src/preprocess_data.py
    - output/dataset.csv
    outs:
    - output/preprocessed_data.joblib
  train:
    cmd: poetry run python src/train.py
    deps:
    - src/train.py
    - output/preprocessed_data.joblib
    outs:
    - output/trained_model_and_data.joblib
  evaluate_model:
    cmd: poetry run python src/evaluate_model.py
    deps:
    - src/evaluate_model.py
    - output/trained_model_and_data.joblib
    outs:
    - output/evaluation.joblib
    metrics:
    - output/accuracy_score.json
