name: Update Coverage Badge

on:
  push:
    branches: ["*"]

jobs:    
  update-badge:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version=1.5.0

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
    
      - name: Install dependencies
        run: poetry -vv install --no-interaction --no-ansi
  
      - name: Add current directory to PYTHONPATH
        run: |
          echo "PYTHONPATH=$PWD" >> "$GITHUB_ENV"

    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: junit-test-report
    #       path: ./tests-report.xml
  
    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: coverage-report
    #       path: ./coverage.xml

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Update badge URL
        run: |
          sed -i "s/{branch}/$GITHUB_REF_SLUG/g" README.md
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update coverage badge URL [skip ci]"
          git push
